Add auth header to get requests
bwyap/github-deploy-status pull request #3
Opened 2019-09-26 14:34 UTC by Drapegnik

For supporting private repos

2020-02-06 15:47 UTC, benedfit commented
@bwyap any chance this could get reviewed and merged?

2020-02-06 23:30 UTC, bwyap commented
@benedfit will look into it!

2020-02-07 01:05 UTC, benyap requested changes
Hi @Drapegnik, thanks for your contribution. Apologies for not getting back, didn't get a chance to review this earlier and it got lost in my list of things to do 😅Just a few small changes required I reckon and it should be good to go!

EDIT: Would be good if you could document the new API in the README too.

2020-02-07 01:05 UTC, benyap commented on src/api.ts
> +  Authorization: `token ${token}`,
There should be an option to **not** have the auth header if we want to access public repos. Seems like currently an auth header will always be sent with the request.

2020-02-07 01:05 UTC, benyap commented on src/api.ts
> +  token: string;
Might be good to add `token` to the `Arguments` interface in `types.d.ts` so the definition is more accurate.

2020-02-10 16:39 UTC, benedfit commented on src/api.ts
> +  Authorization: `token ${token}`,
Would it do any harm to always pass it?

2020-03-11 15:21 UTC, Drapegnik commented on src/api.ts
> +  Authorization: `token ${token}`,
@benedfit, of course no.
@bwyap, I've tested it with my public repo. we can always pass auth token

2020-03-11 15:22 UTC, Drapegnik commented on src/api.ts
> +  token: string;
it's already there

2020-03-11 15:24 UTC, Drapegnik commented on src/api.ts
> +  Authorization: `token ${token}`,
> `--token <token>` - This argument is required.

and valid token is already requirement for all repos

2020-07-22 03:37 UTC, merged